name: pyfortracc
channels:
  - conda-forge
dependencies:
  - pip=25.1
  - python=3.12.11
  # - requests=2.32.4
  # - psutil=7.0.0
  # - ipython=9.3.0
  # - cartopy=0.24.0
  # - geopandas=1.1.1
  # - netcdf4=1.7.2
  # - opencv-python-headless=4.11.0.86
  # - pyarrow=20.0.0
  # - duckdb=1.3.1
  # - rasterio=1.4.3
  # - xarray=2025.6.1
  # - scikit-learn=1.7.0
  # - scipy=1.16.0
  # - shapelysmooth=0.2.1
  # - tqdm=4.67.1
  - pip:
      - ./